### ISSUE TITLE
HFT 实盘时， on_tick 里获取其它期货品牌的历史数据时会出错

### ISSUE THREAD

**Issue by tinyi2018** [wondertrader/wtpy#121]
在 hft 的 on_tick 里调用 np_bars_m_ag = context.stra_get_bars(stdCode= "SHFE.ag.2310" , period="m", count = 30) ， 运行时出错， 提示如下 ：

Exception ignored on calling ctypes callback function: <bound method WtWrapper.on_stra_tick of <wtpy.wrapper.WtWrapper.WtWrapper object at 0x000001434957A3B0>>
Traceback (most recent call last):
  File "D:\CondaPyEnvs\wtpy\lib\site-packages\wtpy\wrapper\WtWrapper.py", line 149, in on_stra_tick
    ctx.on_tick(bytes.decode(stdCode), newTick)
  File "D:\CondaPyEnvs\wtpy\lib\site-packages\wtpy\HftContext.py", line 73, in on_tick
    self.__stra_info__.on_tick(self, stdCode, newTick.contents.to_dict)
  File "E:\Projects\wtpy\workfolder\hft_fut_msg\../Strategies\HftMsg.py", line 80, in on_tick
    np_bars_m_ag = context.stra_get_bars(stdCode= "SHFE.ag.2310" , period="m", count = 30)
  File "D:\CondaPyEnvs\wtpy\lib\site-packages\wtpy\HftContext.py", line 190, in stra_get_bars
    cnt =  self.__wrapper__.hft_get_bars(self.__id__, stdCode, period, count)
TypeError: WtWrapper.hft_get_bars() missing 1 required positional argument: 'isMain'

**Comment by tinyi2018** [comment]
实盘时， 在on_init 里通过context.stra_prepare_bars（）获取期货历史数据， 也会出错。  但在回测时， 不会出现错误， 能返回数据。

**Comment by wondertrader** [comment]
已修复，0.9.9发布
