### ISSUE TITLE
wtpy 0.5.2 version 在ubuntu 18.04上无法运行demo

### ISSUE THREAD

**Issue by qiuwei** [wondertrader/wtpy#3]
运行 `wtpy/demos/cta_stk_bt/runBT.py` 报以下错误：

```
/home/wqiu/.cache/pypoetry/virtualenvs/playground-gu9jURa0-py3.7/lib/python3.7/site-packages/wtpy/wrapper/linux/libWtBtPorter.so
Traceback (most recent call last):
  File "runBT.py", line 7, in <module>
    engine = WtBtEngine(EngineType.ET_CTA)
  File "/home/wqiu/.cache/pypoetry/virtualenvs/playground-gu9jURa0-py3.7/lib/python3.7/site-packages/wtpy/WtBtEngine.py", line 22, in getinstance
    instances[cls] = cls(*args,**kwargs)
  File "/home/wqiu/.cache/pypoetry/virtualenvs/playground-gu9jURa0-py3.7/lib/python3.7/site-packages/wtpy/WtBtEngine.py", line 31, in __init__
    self.__wrapper__ = WtBtWrapper()  #api接口转换器
  File "/home/wqiu/.cache/pypoetry/virtualenvs/playground-gu9jURa0-py3.7/lib/python3.7/site-packages/wtpy/wrapper/WtBtWrapper.py", line 204, in __init__
    self.api = cdll.LoadLibrary(_path)
  File "/home/wqiu/miniconda3/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/home/wqiu/miniconda3/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/wqiu/.cache/pypoetry/virtualenvs/playground-gu9jURa0-py3.7/lib/python3.7/site-packages/wtpy/wrapper/linux/libWtBtPorter.so: undefined symbol: mysql_close
```

**Comment by qiuwei** [comment]
dev分支已经修复。
